---
title: "linearmodel"
author: "Brandon Reyes"
date: "12/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dataF <- read.csv(file="http://onlinestatbook.com/case_studies_rvls/physical_strength/data.txt",sep="",header=TRUE)
```

```{r include=FALSE}
require(tidyverse)
require(tigerstats)
require(knitr)
```



## Now with ggplot - first select the basic data

```{r}
basicNN <- ggplot(dataF,aes(y=SIMS,x=ARM))
```
## Now add in scatterplot

```{r}
basicNN + geom_point()+ geom_smooth(method=lm)
```
  
 
```{r}
basicNN <- ggplot(dataF,aes(y=SIMS,x=GRIP))
```
## Now add in scatterplot

```{r}
basicNN + geom_point()+ geom_smooth(method=lm)
```

```{r}
new <-data.frame(ARM=88,GRIP=94)
predict.lm(model.1,new)
predict(model.1,new,interval="prediction")
```

```{r}
model.1 <- lm(SIMS~ARM,data=dataF)
summary.lm(model.1)
```

```{r}
new <- data.frame(ARM=88,GRIP=94)
          predict.lm(model.2,new)
predict(model.2,new,interval="prediction")
```
```{r}
model.2 <- lm(SIMS~GRIP,data=dataF)
summary.lm(model.2)
``` 

```{r}
new <- data.frame(ARM=88,GRIP=94)
predict.lm(model.3,new)
predict(model.3,new,interval="prediction")
```

```{r}
model.3 <- lm(SIMS~GRIP+ARM,data=dataF)
summary.lm(model.3)
``` 

```{r}
anova(model.1,model.3)
```